services:
  - type: web
    name: portfolio
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
